### PR TITLE
Added function to validate email settings

### PR DESCRIPTION
**Pull request by glennzw**
ValidateSettings attempts to login to the supplied IMAP account to ensure the info is correct.

### CODE REVIEW

**Comment by jprobinson** [comment]
i’m not quite sure I see the utility in this one, sorry. This is just attempting to login and immediately closing the connection.

**Comment by glennzw** [comment]
I'm using it to validate IMAP settings in a larger application. The user has the option to enter IMAP settings, with a 'Test' button to validate the settings are correct and can login.

No worries if it's not for you, I can keep it in my fork.

**Comment by jprobinson** [comment]
While I get the idea, it seems a bit specific for your use case, tbh.

Would it be better to just expose “newIMAPClient” to be public instead?

**Comment by glennzw** [comment]
Ah yes that would probably have been more elegant :) I figured the name ValidateSettings would be useful to the user.

**Comment by jprobinson** [comment]
I've been thinking on it and I'm actually good to bring this helper func in, I think it just needs a name that ties it in with the tooling a tad better. Instead of `ValidateSettings`, how about `ValidateMailboxInfo`?

**Comment by glennzw** [comment]
Sounds like a good idea, I've changed the function name.

**Pull request merged**
